### ISSUE TITLE
publish editable Requirements document

### ISSUE THREAD

**Issue by kmolo** [CCSF-Coders/ccsf_coders_website#1]
Moving issue from https://github.com/mrpaxton/ccsf_coders_website/issues/16

> We will have a file that keep track of the website requirements. We have had requirements as we have already launched the website first time, but those requirements should to be documented and presented to those involved with this website development and for the club members in the next semester.

**Comment by kmolo** [comment]
Should this be created as a [wiki page](https://help.github.com/articles/about-github-wikis/) for [this repo](https://github.com/CCSF-Coders/ccsf_coders_website/wiki)?

**Comment by possibly** [comment]
Not sure on the usefulness of a 'requirements' document. This website seems to have developed on and existed quite well without one this entire time.

Mostly we should keep track of feature requests so coders can sharpen their skills while still feeling useful.
