### ISSUE TITLE
History page

### ISSUE THREAD

**Issue by possibly** [CCSF-Coders/ccsf_coders_website#14]
Page that documents the Coders Club Presidents and Officers, states the clubs mission and anything else we think is critical to the club.

**Comment by possibly** [comment]
Getting started on this today. Already got some good stuff laid out!

Thinking about adding a little timeline of the presidents and a short blurb about them and their contributions to the club. Similar to this: http://codyhouse.co/demo/vertical-timeline/index.html

edit: on second thought, such a flashy vertical timeline does not fit well with the theme :(. Thoughts on pictures of the previous club presidents / officers and a short blurb about them? no? Not sure who the previous officers were though...

edit2: this is what it looks like so far.
![screen shot 2015-06-12 at 10 28 52 am](https://cloud.githubusercontent.com/assets/1417341/8135595/46affb9c-10ed-11e5-8845-2deeea6b7b0a.png)

**Comment by kmolo** [comment]
@possibly Maybe just a listing of officer names without the short blurb.  Blurb is hard to maintain, and can leave some feeling that their work was under- / un- appreciated if they are not mentioned.

**Comment by possibly** [comment]
@kmolo @kevr @jaycenH7, who has been an officer?

Off the top of my head: Katherine Moloney, Chuck Griffin, Jason Hoang, Alex Golubev, Jon Larsen, Tyler Brothers, Alan Martinez, Kevin Morris...I know theres more!

edit: this is the last thing holding me back from updating the website! Woo!

**Comment by kevr** [comment]
Wilson was.
