### ISSUE TITLE
Add twitter link to sidebar on main website

### ISSUE THREAD

**Issue by possibly** [CCSF-Coders/ccsf_coders_website#15]
https://twitter.com/ccsfcoders

This is also the reason the build is 'failing' on the readme :(((((

**Comment by kmolo** [comment]
Anyone?  

I keep posting student-centric content, but only a handful of CCSF student are probably seeing this (those who are following the account).

**Comment by possibly** [comment]
The last pull request from Ian fixed this. We just need to update the website with a git pull (which I just did).
