### ISSUE TITLE
Travis-CI, when merging, does not test the correct build.

### ISSUE THREAD

**Issue by possibly** [CCSF-Coders/ccsf_coders_website#17]
Base Fork (our repo) <-- Merging Fork
Travis CI detects a new merge request, off to go test!
My travisCI code, at one point, does "sudo git clone https://github.com/possibly/ccsf_coders_website.git /var/www"
This clones the repo, WITHOUT THE MERGED FORK, and tests against THE OLD STUFF WE ALREADY KNOW PASSES!

How do we get TravisCI to pull the Merge Request, not the Base Fork?

**Comment by possibly** [comment]
Dug deeper into the issue, + some fixes on my local fork, and fixed this issue. The new problem [is in this log](https://travis-ci.org/possibly/ccsf_coders_website/builds/59899075). Probably some print statements should pin point the issue, but for some reason the tests are not locating elements on the page.

**Comment by possibly** [comment]
HOLY MOLY THIS IS NEVER ENDING. I seriously cant figure out why my tests work flawlessly on my local machine but Selenium fails to "locate element" on Travis. Still working on this...

**Comment by possibly** [comment]
Finally fixed this! Woo! The problem was in the try/catch block I had in my test...so much pain for so little gain. 
![screen shot 2015-06-16 at 4 23 54 pm](https://cloud.githubusercontent.com/assets/1417341/8196727/89f5ae98-1443-11e5-99f0-c9f31a9e051c.png)

**Comment by kmolo** [comment]
woohoo! @possibly is stomping bugs/issues today!
