### ISSUE TITLE
Coding Challenges

### ISSUE THREAD

**Issue by Ian-Hardy** [CCSF-Coders/ccsf_coders_website#18]
List the weekly coding challenge, along with past challenges. Bonus points for being able to submit solutions, see past solution, or link to solution explanations.

**Comment by possibly** [comment]
Worked on this today. This is what it looks like so far.

![ccsfcoders-codingchallenges](https://cloud.githubusercontent.com/assets/1417341/8171948/eb4bfe6e-1370-11e5-835b-0b581b818899.png)

**Comment by possibly** [comment]
Considering this done with the work I just put in on https://github.com/CCSF-Coders/ccsf_coders_website/issues/3
