### ISSUE TITLE
move content of layout divs (page nav, sidebar, footer) into single file(s) - DRY out

### ISSUE THREAD

**Issue by kmolo** [CCSF-Coders/ccsf_coders_website#2]
Moving issue from https://github.com/mrpaxton/ccsf_coders_website/issues/19

> Regarding this issue, we will make the page navigations, footer, and sidebars reside in only one file. We will then have a script to populate the codes and render the html codes for each of the webpage. This will result in the ease of development because we will never have to repeat ourselves when creating new pages or updating some of the common components. Stay [DRY](http://en.wikipedia.org/wiki/Don't_repeat_yourself) :)

Currently have to edit all of the following active files to change the content of these layout divs:
- index.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/index.html)) ([website](https://www.ccsf.edu/coders))
- aboutus.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/aboutus.html)) ([website](http://hills.ccsf.edu/~coders/aboutus.html))
- calendar.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/calendar.html)) ([website](http://hills.ccsf.edu/~coders/calendar.html)) -- only page nav & footer here, no sidebar
- contact.html ([website](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/contact.html)) ([website](http://hills.ccsf.edu/~coders/contact.html))
- history.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/history.html)) ([website](http://hills.ccsf.edu/~coders/history.html))
- irc.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/irc.html)) ([website](http://hills.ccsf.edu/~coders/irc.html))

Also found in these unlinked, but still live files:
- acalc.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/acalc.html)) ([website](http://hills.ccsf.edu/~coders/acalc.html))
- mlinks.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/mlinks.html)) ([website](http://hills.ccsf.edu/~coders/mlinks.html))
- related_clubs.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/related_clubs.html)) ([website](http://hills.ccsf.edu/~coders/related_clubs.html))
- resources.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/resources.html)) ([website](http://hills.ccsf.edu/~coders/resources.html))

The following file doesn't contain any of these layout divs currently:
- gallery.html ([GitHub](https://github.com/CCSF-Coders/ccsf_coders_website/blob/master/gallery.html)) ([website](http://hills.ccsf.edu/~coders/website.html))

**Comment by possibly** [comment]
My modification to the structure of the website (using PHP's require_once functionality) has fixed this issue :).

Modify files in partials/ to update any template or other partial that uses the file you modified.
