### ISSUE TITLE
(Automagically?) Reset website to 'in between semester' state.

### ISSUE THREAD

**Issue by possibly** [CCSF-Coders/ccsf_coders_website#20]
The site now has a bunch of wrong information (we have no meeting times, no location to meet, etc. since its a new semester). The least we can do is 'reset' the website to include 'To be decided soon'-type stuff.

It'd be nice to have a way of running a script / pressing a button and replacing all temporary content like location/meeting times with 'To be decided soon'-type stuff.

**Comment by kmolo** [comment]
I think having a 'in between semester' reset index.html page is a good idea.

Again, I think the 'running a script / pressing a button' solution would work if there wasn't so much turnover, but think about the whole site being handled over to any random person pulled out of a CS class.  Could they updated it?  Could they maintain it?

I think the club website is an organizing tool.

**Comment by kmolo** [comment]
Related to this issue, each semester is seems that a team or a person jumps in and makes a great website, but one that isn't maintainable by the next semester's team.

Seems like a good idea to have a complete reset website that can be reverted to, for when the group that knows how maintain the latest cool version of the website moves on.

**Comment by possibly** [comment]
:( After all this work I put into this site. 

We were able to edit Jason's site the last two semesters. William just wanted to do his own thing with a new website.

I'll be available via email or phone if things need to get updated...
