### ISSUE TITLE
The IRC link is broken

### ISSUE THREAD

**Issue by kmolo** [CCSF-Coders/ccsf_coders_website#21]
@erikcox [wrote](https://github.com/mrpaxton/ccsf_coders_website/issues/40):

> The link to the IRC in the top nav as well as the footer is broken. 
> https://www.nixcode.us/irc returns a 404 error.

/cc @kevr

**Comment by possibly** [comment]
@kevr pays server costs I think and he is always disabling it since mostly people are not on it.

**Comment by kmolo** [comment]
okay, then we just need to remove the link to irc from the website when it won't be available

**Comment by kevr** [comment]
Ah, apologies. I migrated my server a while ago and forgot to setup Kiwi IRC for this link. I'll fix this, tonight!

P.S. the server is still running, the web page is just non-existent.

**Comment by kevr** [comment]
Fixed.

PS. I'll be migrating the IRC daemon over to the new server soon, too, but I'll do it in such a way that it will be a smooth transition as DNS changes.

Thanks,
Kevin

**Comment by kevr** [comment]
Great, just as I say that and fix the webpage, the old server goes down. I guess I'll be migrating now, heh. It'll be down for a little while.

**Comment by kevr** [comment]
K, fixed. All migrated.

**Comment by erikcox** [comment]
Looks good. Thanks.

**Comment by kevr** [comment]
Yeah, by the way, no one really ever used the IRC channel, so it didn't seem like a good plan to keep it running. It was kind of being maintained for no reason. Sorry about that.
