### ISSUE TITLE
Push Updates

### ISSUE THREAD

**Issue by kevr** [CCSF-Coders/ccsf_coders_website#30]
The repository is currently behind the actual website on the host. Please push updates so I can push some changes I've made on my side.

**Comment by akmartinez1** [comment]
I was just checking that this evening myself.  It looks like edits are being made directly to the hills server and not going through GitHub.

Can we somehow get the GitHub repository updated and work from there to keep track of the changes?

Alan

**Comment by kevr** [comment]
Resolved, thanks guys. Ryan Lim, if you need the credentials for hills, let either Alan, Katherine, or I know and we'll help you out.
