### ISSUE TITLE
Website Rewrite

### ISSUE THREAD

**Issue by eliaslfox** [CCSF-Coders/ccsf_coders_website#39]
I started rewriting the website with bootstrap 4, elm, and not php. But I haven't styled it with the hacker vibe. Should we keep the green on black, or move to a more modern dark grey on white?

**Comment by possibly** [comment]
@eliaslfox @kmolo 

Very interested in re-writes of the website, however please keep in mind that when your gone someone else will have to maintain the site. In this light, PHP has a few nice qualities. PHP is old, and thus its easier to find a club member who can modify the website. The way the site is currently written, the PHP doesn't do much. Its mostly HTML. HTML is easy to pickup and modify, and thus its easy to find a club member who can make minor updates to the site.

That said, I think its awesome to use the Coder's club website as a tool for practice! Maybe we can include other versions of the website, like your own, as a separate file under the same domain. So like ccsf.edu/coders/elm. I think almost every semester people get interested in modifying the website, so maybe we could create a /coders/projects page which includes links to projects like yours (/coders/projects/elm).

Thoughts?

-edit-

Checkout #5 , @kevr had a really great idea and if @eliaslfox is into recoding the website, maybe your also up for a bit of php web scraping fun (PHP standard lib can handle this, and pretty well too)?

**Comment by akmartinez1** [comment]
You can also stage a version of the site in your own public_html (hills.ccsf.edu/~yourid/coders) for development and testing and we can look and see how it works from there and copy it over when it’s complete and we; agree that it’s what we want…

**Comment by eliaslfox** [comment]
So I don't currently have hills access, but I can host it somewhere for a preview. 

Although I'm not set on switching to elm from php, I do think it would be a good choice. Elm has been gaining in popularity in the industry, and php has been on a slow decline. Elm is also a very good beginner platform, with a helpful community and very helpful compiler errors.

Php is a relatively well known platform. However, the current code is kinda messy, and rewrite or not, could do with some cleaning up. I think it would be nice for the website to be well written, so it can be used as an example of good software development.

I like the idea of hosting projects on the website, I think it would be a good way to showcase work. 

I read about the webscraping, and I think the idea is cool. It might be easier to use the graphql api than webscrape to get the data though.

**Comment by possibly** [comment]
> Although I'm not set on switching to elm from php, I do think it would be a good choice. Elm has been gaining in popularity in the industry, and php has been on a slow decline. Elm is also a very good beginner platform, with a helpful community and very helpful compiler errors.

I hear that Elm may be gaining popularity, be more of an example of good software development and have a helpful community/toolchain. Do you think that by making Elm the language of the website that the barrier to entry for incoming students would be raised as compared to the current sites PHP/HTML/CSS setup?

**Comment by akmartinez1** [comment]
I’m not set on anything specific but I can say that using a platform that is being taught at the campus is a plus to get members involved too.  I’m taking a PHP class right now and as I get started it’s nice to poke around and see how things work and maybe make improvements from there…

 

No matter what, it’s nie to see this much activity…

**Comment by eliaslfox** [comment]
I think the barrier for incoming students is slightly higher, but mostly because of the different syntax. The vast majority of the code is just generating html, and not that hard to understand. I also think that the barrier of understanding required to maintain the site is now lower. This is due to more explicit dependencies between files, and a reduction of complicated css rules.

**Comment by possibly** [comment]
> I think the barrier for incoming students is slightly higher, but mostly because of the different syntax.

What about for adding new pages to the website? Wouldn't this require more than just knowledge of just the syntax of Elm?

**Comment by eliaslfox** [comment]
Not really, no. I'll break up the structure so the separation of concerns is a little clearer. And then I'll comment the areas where you would need to add a line to add another page. After that all you'll have to do is add a line to the router, and use the home page as an example.

**Comment by eliaslfox** [comment]
My version is now available on gh pages [here](https://eliaslfox.github.io/ccsf_coders_website/). 

@MiLeung said that we only needed the home page. But if there's an interest in transferring over more pages then I can do that.

Also my pr now has proper page routing, which will make adding new pages much easier. Also, I started adding comments to give a bird's eye view of the code structure.

**Comment by possibly** [comment]
Alright then. If there ever were a confusion issue, a future club member could `git revert` back to the PHP state.

**Comment by eliaslfox** [comment]
I think it's safe to close this now. I merged the pr.

**Comment by mileung** [comment]
The CCSF coders website was so simple in the past that having it written in plain html, js, and css seems manageable.

**Comment by kevr** [comment]
my two cents here... though I don't really like PHP personally, I feel like it's a better language to stick with for entry than Elm is; since Elm is kind of a niche language, has it's own style and is not very generic.. there are many frameworks, one could use react, angular, etc, but these don't really help new users with programming paradigms much; they're all specific to their frameworks. Maybe I'm out of the front-end loop, but I've never really heard of Elm being used that much in my experience. Seems like a targeted attempt similar to things like ReactJS that have excelled well past it's popularity. Most people at CCSF, especially the ones learning a lot out of their classes, have not fluently learned javascript, python, php, and are still trying to master them. for those reasons, i don't like the idea of a one-hit framework

**Comment by kevr** [comment]
See [#5](https://github.com/CCSF-Coders/ccsf_coders_website/issues/5) for an updated comment about a utility github API scrape that I committed into the repository. You can easily set up a script using this as a local api, then ajax over to it for JSON data about all CCSF-Coders repositories at any given time.
