### ISSUE TITLE
add comments to HTML/CSS files and introductory links to README to explain jQuery CSS (dcmegamenu)

### ISSUE THREAD

**Issue by kmolo** [CCSF-Coders/ccsf_coders_website#7]
To help future students who are less familiar with jQuery CSS, please add comments to HTML & CSS files and/or introductory links to README, so they can figure out how to update the website styling.

**Comment by possibly** [comment]
No longer an issue as we do everything differently and (hopefully) more simply. We use only basic php (for its 'require' functionality) and the rest is mostly pure html. I've spent quite some time on the README for the site, so hopefully it explains the details of the website and how to edit it well.
