### ISSUE TITLE
Easier way to add new events to the front page.

### ISSUE THREAD

**Issue by possibly** [CCSF-Coders/ccsf_coders_website#9]
Currently, one has to SSH into the hills server and manually edit html files. There's gotta be a better way!

**Comment by kevr** [comment]
Writing a python script for guided manual input with safe-checks that puts valid events as partials into an events/ directory to load in via PHP around the site.

**Comment by kmolo** [comment]
@possibly @kevr I think ssh'ing into hills is fairly simple, given the turnover we can expect for the club.  

Simple HTML and CSS is readable and likely to be editable by future club members.  Remember most club members in the future will only have a class or two of either C++ or Java.  

Though out of date, I've always thought that the LUG homepage -- http://www.ccsf.edu/lug -- is a good example of clear, commented HTML and CSS.

If there were consistent people, then maybe the optimizations you are thinking of would make sense.

**Comment by possibly** [comment]
~~Easily readable HTML / CSS / JavaScript are def. a priority, and always keep in mind the turnover issue. I thought this would be a nice addition to excellently commented HTML for anyone able to read the README.md that rests on the homepage of the GitHub, not a replacement.~~

EDIT: @kmolo @kevr  What are your thoughts on just updating the calendar we have on the front page with events we hold? Its nice that way since managers can just add stuff right there into the calendar without mucking around in code. If someone wants to do it the old fashioned way, they can just add or replace the "welcome" section.

Also, in the new design I just did, the calendar is much more upfront now. (see: https://github.com/CCSF-Coders/ccsf_coders_website/issues/3)

**Comment by possibly** [comment]
Just had an ever better thought
